[project]
name = "brfssdata"

[dependencies]
DBI = "*"
available = "*"
cli = "*"
curl = "*"
dbplyr = "*"
devtools = "*"
dplyr = "*"
duckdb = "*"
gh = "*"
glue = "*"
haven = "*"
httptest2 = "*"
jsonlite = "*"
knitr = "*"
nanoparquet = "*"
piggyback = "*"
pkgdown = "*"
rhub = "*"
rlang = "*"
rmarkdown = "*"
roxygen2 = "*"
rvest = "*"
spelling = "*"
srvyr = "*"
survey = "*"
testthat = "*"
tibble = "*"
urlchecker = "*"
usethis = "*"
xml2 = "*"
